package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.Dealer;
import com.mttl.vlms.entity.DealerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int countByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int deleteByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int insert(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int insertSelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    List<Dealer> selectByExampleWithRowbounds(DealerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    List<Dealer> selectByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    Dealer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dealer record);
}