package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.InspectVehicle;
import com.mttl.vlms.entity.InspectVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InspectVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int countByExample(InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int deleteByExample(InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inspectVehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int insert(InspectVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(InspectVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    List<InspectVehicle> selectByExampleWithRowbounds(InspectVehicleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    List<InspectVehicle> selectByExample(InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    InspectVehicle selectByPrimaryKey(Integer inspectVehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InspectVehicle record, @Param("example") InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InspectVehicle record, @Param("example") InspectVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InspectVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InspectVehicle record);
}