package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.InspectVehicleAttachment;
import com.mttl.vlms.entity.InspectVehicleAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InspectVehicleAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int countByExample(InspectVehicleAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int deleteByExample(InspectVehicleAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inspectVehicleAttachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int insert(InspectVehicleAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int insertSelective(InspectVehicleAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    List<InspectVehicleAttachment> selectByExampleWithRowbounds(InspectVehicleAttachmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    List<InspectVehicleAttachment> selectByExample(InspectVehicleAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    InspectVehicleAttachment selectByPrimaryKey(Integer inspectVehicleAttachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InspectVehicleAttachment record, @Param("example") InspectVehicleAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InspectVehicleAttachment record, @Param("example") InspectVehicleAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InspectVehicleAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_vehicle_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InspectVehicleAttachment record);
}