package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.ItemVehicle;
import com.mttl.vlms.entity.ItemVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ItemVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int countByExample(ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int deleteByExample(ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int insert(ItemVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(ItemVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    List<ItemVehicle> selectByExampleWithRowbounds(ItemVehicleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    List<ItemVehicle> selectByExample(ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    ItemVehicle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ItemVehicle record, @Param("example") ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ItemVehicle record, @Param("example") ItemVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItemVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItemVehicle record);
}