package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.StateDivisionInfo;
import com.mttl.vlms.entity.StateDivisionInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StateDivisionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int countByExample(StateDivisionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int deleteByExample(StateDivisionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int insert(StateDivisionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int insertSelective(StateDivisionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    List<StateDivisionInfo> selectByExampleWithRowbounds(StateDivisionInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    List<StateDivisionInfo> selectByExample(StateDivisionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    StateDivisionInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StateDivisionInfo record, @Param("example") StateDivisionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StateDivisionInfo record, @Param("example") StateDivisionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StateDivisionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StateDivisionInfo record);
}