package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.Trailer;
import com.mttl.vlms.entity.TrailerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TrailerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int countByExample(TrailerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int deleteByExample(TrailerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int insert(Trailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int insertSelective(Trailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    List<Trailer> selectByExampleWithRowbounds(TrailerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    List<Trailer> selectByExample(TrailerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    Trailer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Trailer record, @Param("example") TrailerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Trailer record, @Param("example") TrailerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Trailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Trailer record);
}