package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.VehicleInfo;
import com.mttl.vlms.entity.VehicleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VehicleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int countByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int deleteByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int insert(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int insertSelective(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    List<VehicleInfo> selectByExampleWithRowbounds(VehicleInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    List<VehicleInfo> selectByExample(VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    VehicleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VehicleInfo record, @Param("example") VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VehicleInfo record, @Param("example") VehicleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VehicleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VehicleInfo record);
}