package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.Yard;
import com.mttl.vlms.entity.YardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface YardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int countByExample(YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int deleteByExample(YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int insert(Yard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int insertSelective(Yard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    List<Yard> selectByExampleWithRowbounds(YardExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    List<Yard> selectByExample(YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    Yard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Yard record, @Param("example") YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Yard record, @Param("example") YardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Yard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yard record);
}