package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.ZoneColumn;
import com.mttl.vlms.entity.ZoneColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZoneColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int countByExample(ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int deleteByExample(ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int insert(ZoneColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int insertSelective(ZoneColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    List<ZoneColumn> selectByExampleWithRowbounds(ZoneColumnExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    List<ZoneColumn> selectByExample(ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    ZoneColumn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZoneColumn record, @Param("example") ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZoneColumn record, @Param("example") ZoneColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZoneColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZoneColumn record);
}