package com.mttl.vlms.mapper;

import com.mttl.vlms.entity.ZoneRow;
import com.mttl.vlms.entity.ZoneRowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZoneRowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int countByExample(ZoneRowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int deleteByExample(ZoneRowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int insert(ZoneRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int insertSelective(ZoneRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    List<ZoneRow> selectByExampleWithRowbounds(ZoneRowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    List<ZoneRow> selectByExample(ZoneRowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    ZoneRow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZoneRow record, @Param("example") ZoneRowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZoneRow record, @Param("example") ZoneRowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZoneRow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_row
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZoneRow record);
}