package com.mttl.vlms.entity;

import java.util.Date;

public class BankAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.account_no
     *
     * @mbggenerated
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.swift_code
     *
     * @mbggenerated
     */
    private String swiftCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.branch_name
     *
     * @mbggenerated
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.bank_address
     *
     * @mbggenerated
     */
    private String bankAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.created_by
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.updated_by
     *
     * @mbggenerated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.delete_flg
     *
     * @mbggenerated
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account.currency_type
     *
     * @mbggenerated
     */
    private String currencyType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.id
     *
     * @return the value of bank_account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.id
     *
     * @param id the value for bank_account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_no
     *
     * @return the value of bank_account.account_no
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_no
     *
     * @param accountNo the value for bank_account.account_no
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.bank_name
     *
     * @return the value of bank_account.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.bank_name
     *
     * @param bankName the value for bank_account.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.swift_code
     *
     * @return the value of bank_account.swift_code
     *
     * @mbggenerated
     */
    public String getSwiftCode() {
        return swiftCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.swift_code
     *
     * @param swiftCode the value for bank_account.swift_code
     *
     * @mbggenerated
     */
    public void setSwiftCode(String swiftCode) {
        this.swiftCode = swiftCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.branch_name
     *
     * @return the value of bank_account.branch_name
     *
     * @mbggenerated
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.branch_name
     *
     * @param branchName the value for bank_account.branch_name
     *
     * @mbggenerated
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.bank_address
     *
     * @return the value of bank_account.bank_address
     *
     * @mbggenerated
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.bank_address
     *
     * @param bankAddress the value for bank_account.bank_address
     *
     * @mbggenerated
     */
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.disabled
     *
     * @return the value of bank_account.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.disabled
     *
     * @param disabled the value for bank_account.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.created_by
     *
     * @return the value of bank_account.created_by
     *
     * @mbggenerated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.created_by
     *
     * @param createdBy the value for bank_account.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.updated_by
     *
     * @return the value of bank_account.updated_by
     *
     * @mbggenerated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.updated_by
     *
     * @param updatedBy the value for bank_account.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.created_date
     *
     * @return the value of bank_account.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.created_date
     *
     * @param createdDate the value for bank_account.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.updated_date
     *
     * @return the value of bank_account.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.updated_date
     *
     * @param updatedDate the value for bank_account.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.delete_flg
     *
     * @return the value of bank_account.delete_flg
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.delete_flg
     *
     * @param deleteFlg the value for bank_account.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.currency_type
     *
     * @return the value of bank_account.currency_type
     *
     * @mbggenerated
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.currency_type
     *
     * @param currencyType the value for bank_account.currency_type
     *
     * @mbggenerated
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountNo=").append(accountNo);
        sb.append(", bankName=").append(bankName);
        sb.append(", swiftCode=").append(swiftCode);
        sb.append(", branchName=").append(branchName);
        sb.append(", bankAddress=").append(bankAddress);
        sb.append(", disabled=").append(disabled);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", currencyType=").append(currencyType);
        sb.append("]");
        return sb.toString();
    }
}