package com.mttl.vlms.entity;

import java.util.Date;

public class Driver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.barcode_id
     *
     * @mbggenerated
     */
    private String barcodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_name
     *
     * @mbggenerated
     */
    private String driverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.nrc_no
     *
     * @mbggenerated
     */
    private String nrcNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.date_of_birth
     *
     * @mbggenerated
     */
    private Date dateOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.join_date
     *
     * @mbggenerated
     */
    private Date joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.basic_salary
     *
     * @mbggenerated
     */
    private Double basicSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.license_type
     *
     * @mbggenerated
     */
    private String licenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.license_no
     *
     * @mbggenerated
     */
    private String licenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.license_expire_date
     *
     * @mbggenerated
     */
    private Date licenseExpireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.phone_no
     *
     * @mbggenerated
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.delete_flg
     *
     * @mbggenerated
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.created_user
     *
     * @mbggenerated
     */
    private Integer createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.updated_user
     *
     * @mbggenerated
     */
    private Integer updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.division
     *
     * @mbggenerated
     */
    private Integer division;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.id
     *
     * @return the value of driver.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.id
     *
     * @param id the value for driver.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.barcode_id
     *
     * @return the value of driver.barcode_id
     *
     * @mbggenerated
     */
    public String getBarcodeId() {
        return barcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.barcode_id
     *
     * @param barcodeId the value for driver.barcode_id
     *
     * @mbggenerated
     */
    public void setBarcodeId(String barcodeId) {
        this.barcodeId = barcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_name
     *
     * @return the value of driver.driver_name
     *
     * @mbggenerated
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_name
     *
     * @param driverName the value for driver.driver_name
     *
     * @mbggenerated
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.nrc_no
     *
     * @return the value of driver.nrc_no
     *
     * @mbggenerated
     */
    public String getNrcNo() {
        return nrcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.nrc_no
     *
     * @param nrcNo the value for driver.nrc_no
     *
     * @mbggenerated
     */
    public void setNrcNo(String nrcNo) {
        this.nrcNo = nrcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.date_of_birth
     *
     * @return the value of driver.date_of_birth
     *
     * @mbggenerated
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.date_of_birth
     *
     * @param dateOfBirth the value for driver.date_of_birth
     *
     * @mbggenerated
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.join_date
     *
     * @return the value of driver.join_date
     *
     * @mbggenerated
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.join_date
     *
     * @param joinDate the value for driver.join_date
     *
     * @mbggenerated
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.basic_salary
     *
     * @return the value of driver.basic_salary
     *
     * @mbggenerated
     */
    public Double getBasicSalary() {
        return basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.basic_salary
     *
     * @param basicSalary the value for driver.basic_salary
     *
     * @mbggenerated
     */
    public void setBasicSalary(Double basicSalary) {
        this.basicSalary = basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.license_type
     *
     * @return the value of driver.license_type
     *
     * @mbggenerated
     */
    public String getLicenseType() {
        return licenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.license_type
     *
     * @param licenseType the value for driver.license_type
     *
     * @mbggenerated
     */
    public void setLicenseType(String licenseType) {
        this.licenseType = licenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.license_no
     *
     * @return the value of driver.license_no
     *
     * @mbggenerated
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.license_no
     *
     * @param licenseNo the value for driver.license_no
     *
     * @mbggenerated
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.license_expire_date
     *
     * @return the value of driver.license_expire_date
     *
     * @mbggenerated
     */
    public Date getLicenseExpireDate() {
        return licenseExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.license_expire_date
     *
     * @param licenseExpireDate the value for driver.license_expire_date
     *
     * @mbggenerated
     */
    public void setLicenseExpireDate(Date licenseExpireDate) {
        this.licenseExpireDate = licenseExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.phone_no
     *
     * @return the value of driver.phone_no
     *
     * @mbggenerated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.phone_no
     *
     * @param phoneNo the value for driver.phone_no
     *
     * @mbggenerated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.address
     *
     * @return the value of driver.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.address
     *
     * @param address the value for driver.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.status
     *
     * @return the value of driver.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.status
     *
     * @param status the value for driver.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.disabled
     *
     * @return the value of driver.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.disabled
     *
     * @param disabled the value for driver.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.delete_flg
     *
     * @return the value of driver.delete_flg
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.delete_flg
     *
     * @param deleteFlg the value for driver.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.created_user
     *
     * @return the value of driver.created_user
     *
     * @mbggenerated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.created_user
     *
     * @param createdUser the value for driver.created_user
     *
     * @mbggenerated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.created_date
     *
     * @return the value of driver.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.created_date
     *
     * @param createdDate the value for driver.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.updated_user
     *
     * @return the value of driver.updated_user
     *
     * @mbggenerated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.updated_user
     *
     * @param updatedUser the value for driver.updated_user
     *
     * @mbggenerated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.updated_date
     *
     * @return the value of driver.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.updated_date
     *
     * @param updatedDate the value for driver.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.division
     *
     * @return the value of driver.division
     *
     * @mbggenerated
     */
    public Integer getDivision() {
        return division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.division
     *
     * @param division the value for driver.division
     *
     * @mbggenerated
     */
    public void setDivision(Integer division) {
        this.division = division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.gender
     *
     * @return the value of driver.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.gender
     *
     * @param gender the value for driver.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.type
     *
     * @return the value of driver.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.type
     *
     * @param type the value for driver.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.staff_id
     *
     * @return the value of driver.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.staff_id
     *
     * @param staffId the value for driver.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", barcodeId=").append(barcodeId);
        sb.append(", driverName=").append(driverName);
        sb.append(", nrcNo=").append(nrcNo);
        sb.append(", dateOfBirth=").append(dateOfBirth);
        sb.append(", joinDate=").append(joinDate);
        sb.append(", basicSalary=").append(basicSalary);
        sb.append(", licenseType=").append(licenseType);
        sb.append(", licenseNo=").append(licenseNo);
        sb.append(", licenseExpireDate=").append(licenseExpireDate);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", address=").append(address);
        sb.append(", status=").append(status);
        sb.append(", disabled=").append(disabled);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", division=").append(division);
        sb.append(", gender=").append(gender);
        sb.append(", type=").append(type);
        sb.append(", staffId=").append(staffId);
        sb.append("]");
        return sb.toString();
    }
}