package com.mttl.vlms.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.charges_id
     *
     * @mbggenerated
     */
    private Integer chargesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.unit
     *
     * @mbggenerated
     */
    private Integer unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.unit_price
     *
     * @mbggenerated
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.invoice_id
     *
     * @mbggenerated
     */
    private Integer invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.created_by
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.updated_by
     *
     * @mbggenerated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.delete_flg
     *
     * @mbggenerated
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.task_from_date
     *
     * @mbggenerated
     */
    private Date taskFromDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.task_to_date
     *
     * @mbggenerated
     */
    private Date taskToDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.dealer_id
     *
     * @mbggenerated
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.charges_id
     *
     * @return the value of item.charges_id
     *
     * @mbggenerated
     */
    public Integer getChargesId() {
        return chargesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.charges_id
     *
     * @param chargesId the value for item.charges_id
     *
     * @mbggenerated
     */
    public void setChargesId(Integer chargesId) {
        this.chargesId = chargesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.unit
     *
     * @return the value of item.unit
     *
     * @mbggenerated
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.unit
     *
     * @param unit the value for item.unit
     *
     * @mbggenerated
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.unit_price
     *
     * @return the value of item.unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.unit_price
     *
     * @param unitPrice the value for item.unit_price
     *
     * @mbggenerated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.amount
     *
     * @return the value of item.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.amount
     *
     * @param amount the value for item.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.invoice_id
     *
     * @return the value of item.invoice_id
     *
     * @mbggenerated
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.invoice_id
     *
     * @param invoiceId the value for item.invoice_id
     *
     * @mbggenerated
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.created_by
     *
     * @return the value of item.created_by
     *
     * @mbggenerated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.created_by
     *
     * @param createdBy the value for item.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.updated_by
     *
     * @return the value of item.updated_by
     *
     * @mbggenerated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.updated_by
     *
     * @param updatedBy the value for item.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.delete_flg
     *
     * @return the value of item.delete_flg
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.delete_flg
     *
     * @param deleteFlg the value for item.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.created_date
     *
     * @return the value of item.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.created_date
     *
     * @param createdDate the value for item.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.updated_date
     *
     * @return the value of item.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.updated_date
     *
     * @param updatedDate the value for item.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.description
     *
     * @return the value of item.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.description
     *
     * @param description the value for item.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.task_from_date
     *
     * @return the value of item.task_from_date
     *
     * @mbggenerated
     */
    public Date getTaskFromDate() {
        return taskFromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.task_from_date
     *
     * @param taskFromDate the value for item.task_from_date
     *
     * @mbggenerated
     */
    public void setTaskFromDate(Date taskFromDate) {
        this.taskFromDate = taskFromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.task_to_date
     *
     * @return the value of item.task_to_date
     *
     * @mbggenerated
     */
    public Date getTaskToDate() {
        return taskToDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.task_to_date
     *
     * @param taskToDate the value for item.task_to_date
     *
     * @mbggenerated
     */
    public void setTaskToDate(Date taskToDate) {
        this.taskToDate = taskToDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.dealer_id
     *
     * @return the value of item.dealer_id
     *
     * @mbggenerated
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.dealer_id
     *
     * @param dealerId the value for item.dealer_id
     *
     * @mbggenerated
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.task_id
     *
     * @return the value of item.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.task_id
     *
     * @param taskId the value for item.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", chargesId=").append(chargesId);
        sb.append(", unit=").append(unit);
        sb.append(", unitPrice=").append(unitPrice);
        sb.append(", amount=").append(amount);
        sb.append(", invoiceId=").append(invoiceId);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", description=").append(description);
        sb.append(", taskFromDate=").append(taskFromDate);
        sb.append(", taskToDate=").append(taskToDate);
        sb.append(", dealerId=").append(dealerId);
        sb.append(", taskId=").append(taskId);
        sb.append("]");
        return sb.toString();
    }
}