package com.mttl.vlms.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoginUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public LoginUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table login_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNull() {
            addCriterion("created_user is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNotNull() {
            addCriterion("created_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserEqualTo(Integer value) {
            addCriterion("created_user =", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotEqualTo(Integer value) {
            addCriterion("created_user <>", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThan(Integer value) {
            addCriterion("created_user >", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_user >=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThan(Integer value) {
            addCriterion("created_user <", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThanOrEqualTo(Integer value) {
            addCriterion("created_user <=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIn(List<Integer> values) {
            addCriterion("created_user in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotIn(List<Integer> values) {
            addCriterion("created_user not in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserBetween(Integer value1, Integer value2) {
            addCriterion("created_user between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotBetween(Integer value1, Integer value2) {
            addCriterion("created_user not between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIsNull() {
            addCriterion("updated_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIsNotNull() {
            addCriterion("updated_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserEqualTo(Integer value) {
            addCriterion("updated_user =", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserNotEqualTo(Integer value) {
            addCriterion("updated_user <>", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserGreaterThan(Integer value) {
            addCriterion("updated_user >", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("updated_user >=", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserLessThan(Integer value) {
            addCriterion("updated_user <", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserLessThanOrEqualTo(Integer value) {
            addCriterion("updated_user <=", value, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserIn(List<Integer> values) {
            addCriterion("updated_user in", values, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserNotIn(List<Integer> values) {
            addCriterion("updated_user not in", values, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserBetween(Integer value1, Integer value2) {
            addCriterion("updated_user between", value1, value2, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedUserNotBetween(Integer value1, Integer value2) {
            addCriterion("updated_user not between", value1, value2, "updatedUser");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("updated_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("updated_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("updated_date =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("updated_date <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("updated_date >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_date >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("updated_date <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("updated_date <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("updated_date in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("updated_date not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("updated_date between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("updated_date not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateIsNull() {
            addCriterion("password_change_date is null");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateIsNotNull() {
            addCriterion("password_change_date is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateEqualTo(Date value) {
            addCriterion("password_change_date =", value, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateNotEqualTo(Date value) {
            addCriterion("password_change_date <>", value, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateGreaterThan(Date value) {
            addCriterion("password_change_date >", value, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("password_change_date >=", value, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateLessThan(Date value) {
            addCriterion("password_change_date <", value, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateLessThanOrEqualTo(Date value) {
            addCriterion("password_change_date <=", value, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateIn(List<Date> values) {
            addCriterion("password_change_date in", values, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateNotIn(List<Date> values) {
            addCriterion("password_change_date not in", values, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateBetween(Date value1, Date value2) {
            addCriterion("password_change_date between", value1, value2, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andPasswordChangeDateNotBetween(Date value1, Date value2) {
            addCriterion("password_change_date not between", value1, value2, "passwordChangeDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeIsNull() {
            addCriterion("recovery_code is null");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeIsNotNull() {
            addCriterion("recovery_code is not null");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeEqualTo(String value) {
            addCriterion("recovery_code =", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeNotEqualTo(String value) {
            addCriterion("recovery_code <>", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeGreaterThan(String value) {
            addCriterion("recovery_code >", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("recovery_code >=", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeLessThan(String value) {
            addCriterion("recovery_code <", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeLessThanOrEqualTo(String value) {
            addCriterion("recovery_code <=", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeLike(String value) {
            addCriterion("recovery_code like", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeNotLike(String value) {
            addCriterion("recovery_code not like", value, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeIn(List<String> values) {
            addCriterion("recovery_code in", values, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeNotIn(List<String> values) {
            addCriterion("recovery_code not in", values, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeBetween(String value1, String value2) {
            addCriterion("recovery_code between", value1, value2, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeNotBetween(String value1, String value2) {
            addCriterion("recovery_code not between", value1, value2, "recoveryCode");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeIsNull() {
            addCriterion("recovery_code_time is null");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeIsNotNull() {
            addCriterion("recovery_code_time is not null");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeEqualTo(Date value) {
            addCriterion("recovery_code_time =", value, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeNotEqualTo(Date value) {
            addCriterion("recovery_code_time <>", value, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeGreaterThan(Date value) {
            addCriterion("recovery_code_time >", value, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("recovery_code_time >=", value, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeLessThan(Date value) {
            addCriterion("recovery_code_time <", value, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeLessThanOrEqualTo(Date value) {
            addCriterion("recovery_code_time <=", value, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeIn(List<Date> values) {
            addCriterion("recovery_code_time in", values, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeNotIn(List<Date> values) {
            addCriterion("recovery_code_time not in", values, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeBetween(Date value1, Date value2) {
            addCriterion("recovery_code_time between", value1, value2, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andRecoveryCodeTimeNotBetween(Date value1, Date value2) {
            addCriterion("recovery_code_time not between", value1, value2, "recoveryCodeTime");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagIsNull() {
            addCriterion("site_admin_flag is null");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagIsNotNull() {
            addCriterion("site_admin_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagEqualTo(Boolean value) {
            addCriterion("site_admin_flag =", value, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagNotEqualTo(Boolean value) {
            addCriterion("site_admin_flag <>", value, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagGreaterThan(Boolean value) {
            addCriterion("site_admin_flag >", value, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("site_admin_flag >=", value, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagLessThan(Boolean value) {
            addCriterion("site_admin_flag <", value, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("site_admin_flag <=", value, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagIn(List<Boolean> values) {
            addCriterion("site_admin_flag in", values, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagNotIn(List<Boolean> values) {
            addCriterion("site_admin_flag not in", values, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("site_admin_flag between", value1, value2, "siteAdminFlag");
            return (Criteria) this;
        }

        public Criteria andSiteAdminFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("site_admin_flag not between", value1, value2, "siteAdminFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table login_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table login_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}