package com.mttl.vlms.entity;

import java.util.Date;

public class PortTerminal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.short_name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.full_name
     *
     * @mbggenerated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.phone_no
     *
     * @mbggenerated
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.delete_flg
     *
     * @mbggenerated
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.created_user
     *
     * @mbggenerated
     */
    private Integer createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.updated_user
     *
     * @mbggenerated
     */
    private Integer updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column port_terminal.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.id
     *
     * @return the value of port_terminal.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.id
     *
     * @param id the value for port_terminal.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.short_name
     *
     * @return the value of port_terminal.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.short_name
     *
     * @param shortName the value for port_terminal.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.full_name
     *
     * @return the value of port_terminal.full_name
     *
     * @mbggenerated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.full_name
     *
     * @param fullName the value for port_terminal.full_name
     *
     * @mbggenerated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.phone_no
     *
     * @return the value of port_terminal.phone_no
     *
     * @mbggenerated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.phone_no
     *
     * @param phoneNo the value for port_terminal.phone_no
     *
     * @mbggenerated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.address
     *
     * @return the value of port_terminal.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.address
     *
     * @param address the value for port_terminal.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.description
     *
     * @return the value of port_terminal.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.description
     *
     * @param description the value for port_terminal.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.disabled
     *
     * @return the value of port_terminal.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.disabled
     *
     * @param disabled the value for port_terminal.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.delete_flg
     *
     * @return the value of port_terminal.delete_flg
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.delete_flg
     *
     * @param deleteFlg the value for port_terminal.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.created_user
     *
     * @return the value of port_terminal.created_user
     *
     * @mbggenerated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.created_user
     *
     * @param createdUser the value for port_terminal.created_user
     *
     * @mbggenerated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.created_date
     *
     * @return the value of port_terminal.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.created_date
     *
     * @param createdDate the value for port_terminal.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.updated_user
     *
     * @return the value of port_terminal.updated_user
     *
     * @mbggenerated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.updated_user
     *
     * @param updatedUser the value for port_terminal.updated_user
     *
     * @mbggenerated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column port_terminal.updated_date
     *
     * @return the value of port_terminal.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column port_terminal.updated_date
     *
     * @param updatedDate the value for port_terminal.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table port_terminal
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shortName=").append(shortName);
        sb.append(", fullName=").append(fullName);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", address=").append(address);
        sb.append(", description=").append(description);
        sb.append(", disabled=").append(disabled);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append("]");
        return sb.toString();
    }
}