package com.mttl.vlms.entity;

import java.util.Date;

public class StateDivisionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.state_id
     *
     * @mbggenerated
     */
    private Short stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.state_name
     *
     * @mbggenerated
     */
    private String stateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.isvalid
     *
     * @mbggenerated
     */
    private Short isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state_division_info.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.id
     *
     * @return the value of state_division_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.id
     *
     * @param id the value for state_division_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.state_id
     *
     * @return the value of state_division_info.state_id
     *
     * @mbggenerated
     */
    public Short getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.state_id
     *
     * @param stateId the value for state_division_info.state_id
     *
     * @mbggenerated
     */
    public void setStateId(Short stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.state_name
     *
     * @return the value of state_division_info.state_name
     *
     * @mbggenerated
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.state_name
     *
     * @param stateName the value for state_division_info.state_name
     *
     * @mbggenerated
     */
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.isvalid
     *
     * @return the value of state_division_info.isvalid
     *
     * @mbggenerated
     */
    public Short getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.isvalid
     *
     * @param isvalid the value for state_division_info.isvalid
     *
     * @mbggenerated
     */
    public void setIsvalid(Short isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.created_by
     *
     * @return the value of state_division_info.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.created_by
     *
     * @param createdBy the value for state_division_info.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.updated_by
     *
     * @return the value of state_division_info.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.updated_by
     *
     * @param updatedBy the value for state_division_info.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.created_time
     *
     * @return the value of state_division_info.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.created_time
     *
     * @param createdTime the value for state_division_info.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state_division_info.updated_time
     *
     * @return the value of state_division_info.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state_division_info.updated_time
     *
     * @param updatedTime the value for state_division_info.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state_division_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stateId=").append(stateId);
        sb.append(", stateName=").append(stateName);
        sb.append(", isvalid=").append(isvalid);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}