package com.mttl.vlms.entity;

import java.util.Date;

public class Trailer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.license_no
     *
     * @mbggenerated
     */
    private String licenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.trailer_type
     *
     * @mbggenerated
     */
    private String trailerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.created_by
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.updated_by
     *
     * @mbggenerated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.delete_flg
     *
     * @mbggenerated
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.trailer_code
     *
     * @mbggenerated
     */
    private String trailerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.barcode_id
     *
     * @mbggenerated
     */
    private String barcodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trailer.photo_name
     *
     * @mbggenerated
     */
    private String photoName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.id
     *
     * @return the value of trailer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.id
     *
     * @param id the value for trailer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.license_no
     *
     * @return the value of trailer.license_no
     *
     * @mbggenerated
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.license_no
     *
     * @param licenseNo the value for trailer.license_no
     *
     * @mbggenerated
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.trailer_type
     *
     * @return the value of trailer.trailer_type
     *
     * @mbggenerated
     */
    public String getTrailerType() {
        return trailerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.trailer_type
     *
     * @param trailerType the value for trailer.trailer_type
     *
     * @mbggenerated
     */
    public void setTrailerType(String trailerType) {
        this.trailerType = trailerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.description
     *
     * @return the value of trailer.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.description
     *
     * @param description the value for trailer.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.disabled
     *
     * @return the value of trailer.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.disabled
     *
     * @param disabled the value for trailer.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.created_date
     *
     * @return the value of trailer.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.created_date
     *
     * @param createdDate the value for trailer.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.updated_date
     *
     * @return the value of trailer.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.updated_date
     *
     * @param updatedDate the value for trailer.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.created_by
     *
     * @return the value of trailer.created_by
     *
     * @mbggenerated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.created_by
     *
     * @param createdBy the value for trailer.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.updated_by
     *
     * @return the value of trailer.updated_by
     *
     * @mbggenerated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.updated_by
     *
     * @param updatedBy the value for trailer.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.delete_flg
     *
     * @return the value of trailer.delete_flg
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.delete_flg
     *
     * @param deleteFlg the value for trailer.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.trailer_code
     *
     * @return the value of trailer.trailer_code
     *
     * @mbggenerated
     */
    public String getTrailerCode() {
        return trailerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.trailer_code
     *
     * @param trailerCode the value for trailer.trailer_code
     *
     * @mbggenerated
     */
    public void setTrailerCode(String trailerCode) {
        this.trailerCode = trailerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.barcode_id
     *
     * @return the value of trailer.barcode_id
     *
     * @mbggenerated
     */
    public String getBarcodeId() {
        return barcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.barcode_id
     *
     * @param barcodeId the value for trailer.barcode_id
     *
     * @mbggenerated
     */
    public void setBarcodeId(String barcodeId) {
        this.barcodeId = barcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trailer.photo_name
     *
     * @return the value of trailer.photo_name
     *
     * @mbggenerated
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trailer.photo_name
     *
     * @param photoName the value for trailer.photo_name
     *
     * @mbggenerated
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trailer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", licenseNo=").append(licenseNo);
        sb.append(", trailerType=").append(trailerType);
        sb.append(", description=").append(description);
        sb.append(", disabled=").append(disabled);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", trailerCode=").append(trailerCode);
        sb.append(", barcodeId=").append(barcodeId);
        sb.append(", photoName=").append(photoName);
        sb.append("]");
        return sb.toString();
    }
}