package com.mttl.vlms.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.barcode_id
     *
     * @mbggenerated
     */
    private String barcodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.date_of_birth
     *
     * @mbggenerated
     */
    private Date dateOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nrc_no
     *
     * @mbggenerated
     */
    private String nrcNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_no
     *
     * @mbggenerated
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.created_by
     *
     * @mbggenerated
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.updated_by
     *
     * @mbggenerated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.delete_flg
     *
     * @mbggenerated
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.login_id
     *
     * @mbggenerated
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.yard_id
     *
     * @mbggenerated
     */
    private Integer yardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.join_date
     *
     * @mbggenerated
     */
    private Date joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password_change_date
     *
     * @mbggenerated
     */
    private Date passwordChangeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.barcode_id
     *
     * @return the value of user_info.barcode_id
     *
     * @mbggenerated
     */
    public String getBarcodeId() {
        return barcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.barcode_id
     *
     * @param barcodeId the value for user_info.barcode_id
     *
     * @mbggenerated
     */
    public void setBarcodeId(String barcodeId) {
        this.barcodeId = barcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.date_of_birth
     *
     * @return the value of user_info.date_of_birth
     *
     * @mbggenerated
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.date_of_birth
     *
     * @param dateOfBirth the value for user_info.date_of_birth
     *
     * @mbggenerated
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nrc_no
     *
     * @return the value of user_info.nrc_no
     *
     * @mbggenerated
     */
    public String getNrcNo() {
        return nrcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nrc_no
     *
     * @param nrcNo the value for user_info.nrc_no
     *
     * @mbggenerated
     */
    public void setNrcNo(String nrcNo) {
        this.nrcNo = nrcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_no
     *
     * @return the value of user_info.phone_no
     *
     * @mbggenerated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_no
     *
     * @param phoneNo the value for user_info.phone_no
     *
     * @mbggenerated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.department
     *
     * @return the value of user_info.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.department
     *
     * @param department the value for user_info.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.disabled
     *
     * @return the value of user_info.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.disabled
     *
     * @param disabled the value for user_info.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.created_date
     *
     * @return the value of user_info.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.created_date
     *
     * @param createdDate the value for user_info.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.updated_date
     *
     * @return the value of user_info.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.updated_date
     *
     * @param updatedDate the value for user_info.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.created_by
     *
     * @return the value of user_info.created_by
     *
     * @mbggenerated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.created_by
     *
     * @param createdBy the value for user_info.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.updated_by
     *
     * @return the value of user_info.updated_by
     *
     * @mbggenerated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.updated_by
     *
     * @param updatedBy the value for user_info.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.delete_flg
     *
     * @return the value of user_info.delete_flg
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.delete_flg
     *
     * @param deleteFlg the value for user_info.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.description
     *
     * @return the value of user_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.description
     *
     * @param description the value for user_info.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.role_id
     *
     * @return the value of user_info.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.role_id
     *
     * @param roleId the value for user_info.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.login_id
     *
     * @return the value of user_info.login_id
     *
     * @mbggenerated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.login_id
     *
     * @param loginId the value for user_info.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.yard_id
     *
     * @return the value of user_info.yard_id
     *
     * @mbggenerated
     */
    public Integer getYardId() {
        return yardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.yard_id
     *
     * @param yardId the value for user_info.yard_id
     *
     * @mbggenerated
     */
    public void setYardId(Integer yardId) {
        this.yardId = yardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.join_date
     *
     * @return the value of user_info.join_date
     *
     * @mbggenerated
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.join_date
     *
     * @param joinDate the value for user_info.join_date
     *
     * @mbggenerated
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.staff_id
     *
     * @return the value of user_info.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.staff_id
     *
     * @param staffId the value for user_info.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password_change_date
     *
     * @return the value of user_info.password_change_date
     *
     * @mbggenerated
     */
    public Date getPasswordChangeDate() {
        return passwordChangeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password_change_date
     *
     * @param passwordChangeDate the value for user_info.password_change_date
     *
     * @mbggenerated
     */
    public void setPasswordChangeDate(Date passwordChangeDate) {
        this.passwordChangeDate = passwordChangeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", barcodeId=").append(barcodeId);
        sb.append(", name=").append(name);
        sb.append(", dateOfBirth=").append(dateOfBirth);
        sb.append(", nrcNo=").append(nrcNo);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", department=").append(department);
        sb.append(", address=").append(address);
        sb.append(", disabled=").append(disabled);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", description=").append(description);
        sb.append(", roleId=").append(roleId);
        sb.append(", loginId=").append(loginId);
        sb.append(", password=").append(password);
        sb.append(", gender=").append(gender);
        sb.append(", status=").append(status);
        sb.append(", yardId=").append(yardId);
        sb.append(", joinDate=").append(joinDate);
        sb.append(", staffId=").append(staffId);
        sb.append(", passwordChangeDate=").append(passwordChangeDate);
        sb.append("]");
        return sb.toString();
    }
}