package com.mttl.vlms.entity;

import java.util.Date;

public class Zone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.yard_id
     *
     * @mbggenerated
     */
    private Integer yardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.disabled
     *
     * @mbggenerated
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.delete_flg
     *
     * @mbggenerated
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.created_user
     *
     * @mbggenerated
     */
    private Integer createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.updated_user
     *
     * @mbggenerated
     */
    private Integer updatedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.is_extra_zone
     *
     * @mbggenerated
     */
    private Boolean isExtraZone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.id
     *
     * @return the value of zone.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.id
     *
     * @param id the value for zone.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.yard_id
     *
     * @return the value of zone.yard_id
     *
     * @mbggenerated
     */
    public Integer getYardId() {
        return yardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.yard_id
     *
     * @param yardId the value for zone.yard_id
     *
     * @mbggenerated
     */
    public void setYardId(Integer yardId) {
        this.yardId = yardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.name
     *
     * @return the value of zone.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.name
     *
     * @param name the value for zone.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.disabled
     *
     * @return the value of zone.disabled
     *
     * @mbggenerated
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.disabled
     *
     * @param disabled the value for zone.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.delete_flg
     *
     * @return the value of zone.delete_flg
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.delete_flg
     *
     * @param deleteFlg the value for zone.delete_flg
     *
     * @mbggenerated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.created_user
     *
     * @return the value of zone.created_user
     *
     * @mbggenerated
     */
    public Integer getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.created_user
     *
     * @param createdUser the value for zone.created_user
     *
     * @mbggenerated
     */
    public void setCreatedUser(Integer createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.created_date
     *
     * @return the value of zone.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.created_date
     *
     * @param createdDate the value for zone.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.updated_user
     *
     * @return the value of zone.updated_user
     *
     * @mbggenerated
     */
    public Integer getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.updated_user
     *
     * @param updatedUser the value for zone.updated_user
     *
     * @mbggenerated
     */
    public void setUpdatedUser(Integer updatedUser) {
        this.updatedUser = updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.updated_date
     *
     * @return the value of zone.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.updated_date
     *
     * @param updatedDate the value for zone.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.is_extra_zone
     *
     * @return the value of zone.is_extra_zone
     *
     * @mbggenerated
     */
    public Boolean getIsExtraZone() {
        return isExtraZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.is_extra_zone
     *
     * @param isExtraZone the value for zone.is_extra_zone
     *
     * @mbggenerated
     */
    public void setIsExtraZone(Boolean isExtraZone) {
        this.isExtraZone = isExtraZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", yardId=").append(yardId);
        sb.append(", name=").append(name);
        sb.append(", disabled=").append(disabled);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", isExtraZone=").append(isExtraZone);
        sb.append("]");
        return sb.toString();
    }
}